In [ ]:
# Run first block below then follow instructions

In [ ]:
pip install git+https://github.com/billybraith17/billiespnet

In [ ]:
# Once block above has run, open the files and find usr/local/lib/python3.7/dist-packages/ESPnet2/bin.tts_inference.py
# delete this file then upload the tts_inference.py file from billy-notebooks in my GitHub billiespnet
# continue running the rest of the code

In [ ]:
pip install torch espnet espnet_model_zoo parallel_wavegan==0.5.4

In [ ]:
%%bash
!(stat -t /usr/local/lib/*/dist-packages/google/colab > /dev/null 2>&1) && exit 
pip install ninja 2>> install.log
git clone https://github.com/SIDN-IAP/global-model-repr.git tutorial_code 2>> install.log
# git clone https://github.com/billybraith17/global-model-repr.git tutorial_code 2>> install.log

In [ ]:
try: # set up path
    import google.colab, sys, torch
    sys.path.append('/content/tutorial_code')
    if not torch.cuda.is_available():
        print("Change runtime type to include a GPU.")  
except:
    pass

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib as mpl

In [ ]:
import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Running pytorch', torch.__version__, 'using', device.type)

In [ ]:
import torchvision
import torch.hub

# using the global-model-repr package
from netdissect import nethook, proggan

In [ ]:
# def from_pretrained2(
#     model_tag: Optional[str] = None,
#     vocoder_tag: Optional[str] = None,
#     **kwargs: Optional[Any],
# ):
"""Build Text2Speech instance from the pretrained model.
Args:
    model_tag (Optional[str]): Model tag of the pretrained models.
        Currently, the tags of espnet_model_zoo are supported.
    vocoder_tag (Optional[str]): Vocoder tag of the pretrained vocoders.
        Currently, the tags of parallel_wavegan are supported, which should
        start with the prefix "parallel_wavegan/".
Returns:
    Text2Speech: Text2Speech instance.
"""

from espnet2.bin.tts_inference import Text2Speech
from espnet2.bin.tts_inference import Text2Speech2

model_tag = 'kan-bayashi/vctk_xvector_conformer_fastspeech2' #@param ["kan-bayashi/vctk_gst_tacotron2", "kan-bayashi/vctk_gst_transformer", "kan-bayashi/vctk_xvector_tacotron2", "kan-bayashi/vctk_xvector_transformer", "kan-bayashi/vctk_xvector_conformer_fastspeech2", "kan-bayashi/vctk_gst+xvector_tacotron2", "kan-bayashi/vctk_gst+xvector_transformer", "kan-bayashi/vctk_gst+xvector_conformer_fastspeech2", "kan-bayashi/vctk_multi_spk_vits", "kan-bayashi/vctk_full_band_multi_spk_vits", "kan-bayashi/libritts_xvector_transformer", "kan-bayashi/libritts_xvector_conformer_fastspeech2", "kan-bayashi/libritts_gst+xvector_transformer", "kan-bayashi/libritts_gst+xvector_conformer_fastspeech2", "kan-bayashi/libritts_xvector_vits"] {type:"string"}
vocoder_tag = "parallel_wavegan/vctk_hifigan.v1"  #@param ["none", "parallel_wavegan/vctk_parallel_wavegan.v1.long", "parallel_wavegan/vctk_multi_band_melgan.v2", "parallel_wavegan/vctk_style_melgan.v1", "parallel_wavegan/vctk_hifigan.v1", "parallel_wavegan/libritts_parallel_wavegan.v1.long", "parallel_wavegan/libritts_multi_band_melgan.v2", "parallel_wavegan/libritts_hifigan.v1", "parallel_wavegan/libritts_style_melgan.v1"] {type:"string"}
kwargs = {
    # Only for Tacotron 2 & Transformer
    "threshold" : 0.5,
    # Only for Tacotron 2
    "minlenratio" : 0.0,
    "maxlenratio" : 10.0,
    "use_att_constraint" : False,
    "backward_window" : 1,
    "forward_window" : 3,
    # Only for FastSpeech & FastSpeech2 & VITS
    "speed_control_alpha" : 1.0,
    # Only for VITS
    "noise_scale" : 0.333,
    "noise_scale_dur" : 0.333,
}

# print(kwargs["noise_scale"])
# model_tag: Optional[str] = None
# vocoder_tag: Optional[str] = None
# **kwargs: Optional[Any]


if model_tag is not None:
    try:
        from espnet_model_zoo.downloader import ModelDownloader

    except ImportError:
        logging.error(
            "`espnet_model_zoo` is not installed. "
            "Please install via `pip install -U espnet_model_zoo`."
        )
        raise
    d = ModelDownloader()
    kwargs.update(**d.download_and_unpack(model_tag))

if vocoder_tag is not None:
    if vocoder_tag.startswith("parallel_wavegan/"):
        try:
            from parallel_wavegan.utils import download_pretrained_model

        except ImportError:
            logging.error(
                "`parallel_wavegan` is not installed. "
                "Please install via `pip install -U parallel_wavegan`."
            )
            raise

        from parallel_wavegan import __version__
        from packaging.version import parse as V
        from pathlib import Path

        # NOTE(kan-bayashi): Filelock download is supported from 0.5.2
        assert V(__version__) > V("0.5.1"), (
            "Please install the latest parallel_wavegan "
            "via `pip install -U parallel_wavegan`."
        )
        vocoder_tag = vocoder_tag.replace("parallel_wavegan/", "")
        vocoder_file = download_pretrained_model(vocoder_tag)
        vocoder_config = Path(vocoder_file).parent / "config.yml"
        kwargs.update(vocoder_config=vocoder_config, vocoder_file=vocoder_file)

    else:
        raise ValueError(f"{vocoder_tag} is unsupported format.")

# __init__
text2speech = Text2Speech(**kwargs)
text2speech2 = Text2Speech2(**kwargs)

In [ ]:
# Wrap the vocoder
from netdissect import nethook
layer = 'vocoder.blocks.9.convs2.1.1'    #@param ["vocoder.last_conv_layers.0", "vocoder.last_conv_layers.1", "vocoder.last_conv_layers.2", "vocoder.last_conv_layers.3", "vocoder.conv_layers.6.conv", "vocoder.conv_layers.6.conv1x1_aux", "vocoder.conv_layers.6.conv1x1_out", "vocoder.conv_layers.6.conv1x1_skip", "vocoder.first_conv", "vocoder.upsample_net.conv_in", "vocoder.upsample_net.upsample.up_layers.6", "vocoder.upsample_net.upsample.up_layers.7", "vocoder.melgan.0", "vocoder.melgan.19.stack.4", "vocoder.melgan.23", "vocoder.pqmf.pad_fn", "vocoder.blocks.7.upsample", "vocoder.output_conv.1", "vocoder.blocks.11.convs2.0.1", "vocoder.output_conv.2", "vocoder.blocks.0.convs1.1.1", "vocoder.blocks.1.convs1.1.1", "vocoder.blocks.4.convs1.1.1", "vocoder.blocks.7.convs1.1.1", "vocoder.blocks.7.convs1.2.1", "vocoder.blocks.8.convs1.2.1", "vocoder.blocks.9.convs1.1.1", "vocoder.blocks.9.convs2.1.1",  "vocoder.blocks.10.convs1.1.1",  "vocoder.blocks.10.convs2.1.1", "vocoder.blocks.11.convs2.1.1", "vocoder.blocks.0.convs1.1.0", "vocoder.blocks.1.convs1.2.0", "vocoder.blocks.4.convs1.1.0", "vocoder.blocks.7.convs1.1.0", "vocoder.blocks.7.convs1.2.0", "vocoder.blocks.7.convs2.0.0", "vocoder.blocks.8.convs1.2.0", "vocoder.blocks.9.convs1.1.0", "vocoder.blocks.9.convs2.1.0",  "vocoder.blocks.10.convs1.1.0",  "vocoder.blocks.10.convs2.1.0", "vocoder.blocks.11.convs2.1.0"] {type:"string"}


# Don't re-wrap it, if it's already wrapped (e.g., if you press enter twice)
if not isinstance(text2speech.vocoder, nethook.InstrumentedModel):
    text2speech.vocoder = nethook.InstrumentedModel(text2speech.vocoder)
    text2speech2.vocoder = nethook.InstrumentedModel(text2speech2.vocoder)

text2speech.vocoder.retain_layer(layer)
text2speech2.vocoder.retain_layer(layer)

In [ ]:
text2speech.vocoder

# text2speech.vocoder.retain_layer('vocoder')

In [ ]:
import glob
import os
import numpy as np
import kaldiio

# Get model directory path
from espnet_model_zoo.downloader import ModelDownloader
d = ModelDownloader()
model_dir = os.path.dirname(d.download_and_unpack(model_tag)["train_config"])

# X-vector selection
# We only need the x-vector part at that's what this model uses. The ones with 
spembs = None
if text2speech.use_spembs:
  xvector_ark = [p for p in glob.glob(f"{model_dir}/../../dump/**/spk_xvector.ark", recursive=True) if "tr" in p][0]
  xvectors = {k: v for k, v in kaldiio.load_ark(xvector_ark)}
  spks = list(xvectors.keys())

In [ ]:
from netdissect import tally
x = "Please call Stella. Ask her to."

# To collect stats, define a function that returns 2d [samples, units]
def compute_samples(index):
    # print(index)
    spk = spks[int(index[0])]
    spembs = xvectors[spk]
    wav = text2speech(x, spembs=spembs)["wav"]
    acts = text2speech.vocoder.retained_layer(layer)
    acts = torch.flatten(acts, start_dim=1)
    acts_stack = acts
    print(acts.shape)
    # print(acts)
    # acts_stack = acts[0]

    for i in index[1:7]:
      spk = spks[int(i)]
      spembs = xvectors[spk]
      wav = text2speech(x, spembs=spembs)["wav"]
      # acts = model.retained_layer('layer4') # get the activations, and flatten
      acts = text2speech.vocoder.retained_layer(layer)
      # print(acts[0].shape)
      # print(acts)
      acts = torch.flatten(acts, start_dim=1)

      acts_stack = torch.cat((acts_stack, acts), 0)
      print(acts_stack.shape)

    for i in index[7:]:
      spk = spks[int(i)]
      spembs = xvectors[spk]
      wav = text2speech2(x, spembs=spembs)["wav"]
      # acts = model.retained_layer('layer4') # get the activations, and flatten
      acts = text2speech2.vocoder.retained_layer(layer)
      # print(acts[0].shape)
      # print(acts)
      acts = torch.flatten(acts, start_dim=1)

      acts_stack = torch.cat((acts_stack, acts), 0)
      print(acts_stack.shape)

    return acts_stack


from torch.utils.data import TensorDataset
# Define our batch of inputs to the model
# zds = TensorDataset(torch.linspace(0, 49, 50))
# this also works
zds = torch.linspace(0, 107, 108)

# Then tally_quantile will run your function over the whole dataset to collect quantile stats
# rq = tally.tally_quantile(compute_samples, zds, batch_size=10)

# Print out the median value for the first 20 channels
# print(rq.quantiles(0.9)[:20])
# print(rq.mean())

In [ ]:
# print(rq.quantiles(1)[:20])

In [ ]:
# Then tally_quantile will run your function over the whole dataset to collect quantile stats
rq = tally.tally_quantile(compute_samples, zds, batch_size=10)

# Print out the median value for the first 20 channels
print(rq.quantiles(0.99).shape)

In [ ]:
topk = tally.tally_topk(compute_samples, zds)
topk.result()[1].shape

In [ ]:
text2speech.vocoder.retained_layer(layer).shape

torch.Size([1, 32, 30000])

In [ ]:
topk.result()[1]

tensor([[ 55,  48,   0,  ...,  96,  87,  33],
        [ 43,  27,  15,  ...,  49,  69,  95],
        [ 27,  51,  82,  ...,  89,  10,  88],
        ...,
        [ 20,   3,  54,  ...,  97, 107,  57],
        [  3,  54,  71,  ...,  89,  98,  68],
        [ 63,   0,  84,  ...,  97,  87,  18]])

In [ ]:
topk.result()[0]

tensor([[ -0.4345,  -0.4680,  -0.4685,  ...,  -0.6590,  -0.6594,  -0.6624],
        [ -0.4367,  -0.4499,  -0.4822,  ...,  -0.7512,  -0.7620,  -0.7726],
        [ -0.2456,  -0.2827,  -0.3312,  ...,  -0.6479,  -0.6534,  -0.6542],
        ...,
        [  1.0232,   0.8102,   0.7671,  ...,  -3.4512,  -3.4512,  -3.4512],
        [  0.5919,   0.5436,   0.3847,  ...,  -5.1450,  -5.1450,  -5.1450],
        [ -0.0142,  -0.1528,  -0.1683,  ..., -11.0434, -11.0434, -11.0434]])

In [ ]:
southern_units = {0, 3, 4, 6, 7, 14, 30, 31, 41}
s_african_units = {82, 86, 93, 99}
indian = {21, 24, 107}
scottish = {9, 11, 15, 19, 20, 22, 25, 28, 33, 35, 36, 37, 38, 44, 45, 48, 54, 57, 58}
irish = {18, 39, 56, 61, 65, 67, 81, 95, 105}
dublin = {18, 61, 65, 95}
n_irish = {12, 34, 62, 63, 73, 100}
belfast = {12, 34, 62, 63, 73}
cali = {64, 68, 69, 85}
yorkshire = {40, 43, 60}
NE = {42, 50, 55, 59}
canada = {71, 72, 76, 80, 83, 84, 97, 104}

female = {0, 3,4,5,6, 8, 9, 10, 12, 13, 14, 17, 21, 22, 23, 26, 30, 34, 35, 37, 38, 39, 40, 41, 42, 49, 50, 53, 55, 56, 61, 63, 64, 65, 66, 68, 69, 70, 72, 74, 75, 76, 77, 78, 80, 81,82, 84, 85, 86, 88, 89, 90, 92,93,94,95,96,97, 100, 102,103}
male = {1, 2, 7, 11, 15, 16, 18, 19, 20, 24, 25, 27, 28, 29, 31, 32, 33, 36, 43, 44, 45, 46, 47, 48, 51, 52, 54, 57, 58, 59, 60, 62, 67, 71, 73, 79, 83, 87, 91, 98, 99, 101, 104, 105, 106, 107}
edited = {7,8,9, 17,18,19, 27,28,29, 37,38,39, 47,48,49, 57,58,59, 67,68,69, 77,78,79, 87,88,89, 97,98,99, 107}

In [ ]:
# selecting the first 5 indices from the first row / unit
top = topk.result()[1][0][0:5]
print(top)
# casting from tensor to set 
top = set(top.tolist())

# calculating IoU
num = top.intersection(edited)
print(num)
den = top.union(edited)
print(den)
IoU = len(num) / len(den)
print(IoU)

tensor([55, 48,  0, 41, 17])
{48, 17}
{0, 7, 8, 9, 17, 18, 19, 27, 28, 29, 37, 38, 39, 41, 47, 48, 49, 55, 57, 58, 59, 67, 68, 69, 77, 78, 79, 87, 88, 89, 97, 98, 99, 107}
0.058823529411764705


In [ ]:
# Quick method
# iterating st we can calculate the IoU for all units in the layer
IoU_list = []
chosen_property = edited
result = topk.result()[1]
result = result.tolist()
# len(result)

for i in range(0, topk.result()[1].shape[0]):
  top = result[i][0:5]
  top = set(top)
  num = top.intersection(chosen_property)
  den = top.union(chosen_property)
  IoU_list.append(len(num) / len(den))
  # print(i)

# top = set(top.tolist())
# for i in range(0, topk.result()[1].shape[0]):
#   num = top.intersection(southern_units)
#   den = top.union(southern_units)
#   IoU_list.append(len(num) / len(den))
#   print(i)

In [ ]:
len(IoU_list)

960000

In [ ]:
# IoU_list

In [ ]:
# setting the number of units we want to change the actication to the top 1% quantile for and printing their indices
n_units = 40000
IoU_list = torch.tensor(IoU_list)
top_IoU = torch.topk(IoU_list, n_units)
# print(layer, '\n', top_IoU, '\n')
# print(top_IoU[1].shape)
# Indices of random nodes within this layer to change the activation of
rand_IoU = torch.randint(0, len(IoU_list), (n_units,))
# print(rand_IoU)


In [ ]:
# # setting the number of units we want to change the activations of to 0 and printing their indices
# n_units_z = 400000
# IoU_list_z = torch.tensor(IoU_list_z)
# top_IoU_z = torch.topk(IoU_list_z, n_units_z)
# print(layer, '\n', top_IoU_z, '\n')

In [ ]:
# top_IoU[1][1]

In [ ]:
# defining functions to get the unit's index from the number layer and its index from topk
def index_map(layer1, idx):
    div = text2speech.vocoder.retained_layer(layer1).shape[2]
    first = idx//div
    second = idx%div
    return [0, first, second]


# index_map_list(layer, top_IoU[1].numpy())

In [ ]:
# function to set units to the top 1% quantile
def change_units(data, model):
    # for i in range(0, n_units_z):
    #   temp = index_map(layer, top_IoU_z[1][i])
    #   data[0, temp[1], temp[2]] = 0

    quant = rq.quantiles(0.99)
    for i in range(0, n_units):
#     if want to only change the top IoU nodes
      temp = index_map(layer, top_IoU[1][i])
      # if want to change the same number of random nodes
      # temp = index_map(layer, rand_IoU[i])
      data[0, temp[1], temp[2]] = quant[top_IoU[1][i]]

    return data

# setting units to top 1%
text2speech.vocoder.edit_layer(layer, rule=change_units)


# # function to set units to 0
# def zero_units(data, model):
#     for i in range(0, n_units_z):
#       temp = index_map(layer, top_IoU_z[1][i])
#       data[0, temp[1], temp[2]] = 0

#     return data

# setting units to top 1%
# text2speech.vocoder.edit_layer(layer, rule=zero_units)

In [ ]:
spk = spks[10]
spembs = xvectors[spk]
print(f"selected spk: {spk}")

selected spk: p236


In [ ]:
import soundfile as sf
import time
# x = "Please call Stella. Ask her to bring these things with her from the store:  Six spoons of fresh snow peas, five thick slabs of blue cheese, and maybe a snack for her brother Bob.  We also need a small plastic snake and a big toy frog for the kids.  She can scoop these things into three red bags, and we will go meet her Wednesday at the train station."
x = "Please call Stella.  Ask her too."
# x = "Bring these things with her from the store."

# __call__
wav = text2speech(x, spembs=spembs)["wav"]
# print(text2speech(x, spembs=spembs)["feat_gen"].shape)
# print(text2speech(x, spembs=spembs)["feat_gen_denorm"].shape)

sf.write("out.wav", wav.numpy(), 24000, "PCM_16")

# Display the audio file below
from IPython.display import display, Audio
display(Audio(wav.view(-1).cpu().numpy(), rate=24000))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  after removing the cwd from sys.path.


In [ ]:
import soundfile as sf
import time
# x = "Please call Stella. Ask her to bring these things with her from the store:  Six spoons of fresh snow peas, five thick slabs of blue cheese, and maybe a snack for her brother Bob.  We also need a small plastic snake and a big toy frog for the kids.  She can scoop these things into three red bags, and we will go meet her Wednesday at the train station."
x = "Please call Stella.  Ask her too."
# __call__
wav = text2speech2(x, spembs=spembs)["wav"]
# print(text2speech(x, spembs=spembs)["feat_gen"].shape)
# print(text2speech(x, spembs=spembs)["feat_gen_denorm"].shape)

sf.write("out.wav", wav.numpy(), 24000, "PCM_16")

# Display the audio file below
from IPython.display import display, Audio
display(Audio(wav.view(-1).cpu().numpy(), rate=24000))

In [ ]:
text2speech.vocoder.remove_edits()

In [ ]:
x = "Please call Stella.  Ask her too."
# __call__
wav = text2speech(x, spembs=spembs)["wav"]
# print(text2speech(x, spembs=spembs)["feat_gen"].shape)
# print(text2speech(x, spembs=spembs)["feat_gen_denorm"].shape)

sf.write("out.wav", wav.numpy(), 24000, "PCM_16")

# Display the audio file below
from IPython.display import display, Audio
display(Audio(wav.view(-1).cpu().numpy(), rate=24000))

In [ ]:
# testing the units had chage to e.g. 1 when we edited them using our new function
text2speech.vocoder.retained_layer(layer)[0][30][500:520]

tensor([2.5679, 2.8476, 2.7695, 3.2227, 2.7628, 3.1868, 2.6966, 2.8452, 2.9820,
        3.1208, 2.8697, 3.0869, 2.8437, 2.8014, 2.9307, 3.2791, 2.7044, 2.9206,
        2.9258, 3.0601])

In [ ]:
text2speech.vocoder.retained_layer(layer).shape

torch.Size([1, 64, 10000])